-- Demo Data: 100 Real Generic Drugs
-- Run this after the DDL and before related entity inserts

BEGIN;

INSERT INTO generic_drugs (row, generic_key, generic_name, biologic, mech_of_action, class_or_type, target) VALUES
    (1, 'adalimumab', 'Adalimumab', 'Yes', 'TNF Blocker', 'Biologic', 'TNFi'),
    (2, 'infliximab', 'Infliximab', 'Yes', 'TNF Blocker', 'Biologic', 'TNFi'),
    (3, 'etanercept', 'Etanercept', 'Yes', 'TNF Blocker', 'Biologic', 'TNFi'),
    (4, 'rituximab', 'Rituximab', 'Yes', 'CD20 Blocker', 'Biologic', 'CD20i'),
    (5, 'tocilizumab', 'Tocilizumab', 'Yes', 'IL-6 Blocker', 'Biologic', 'IL6i'),
    (6, 'abatacept', 'Abatacept', 'Yes', 'T-cell Inhibitor', 'Biologic', 'CTLAi'),
    (7, 'anakinra', 'Anakinra', 'Yes', 'IL-1 Blocker', 'Biologic', 'IL1i'),
    (8, 'certolizumab', 'Certolizumab', 'Yes', 'TNF Blocker', 'Biologic', 'TNFi'),
    (9, 'golimumab', 'Golimumab', 'Yes', 'TNF Blocker', 'Biologic', 'TNFi'),
    (10, 'tofacitinib', 'Tofacitinib', 'No', 'JAK inhibitor', 'Small Molecule', 'JAKi'),
    (11, 'baricitinib', 'Baricitinib', 'No', 'JAK inhibitor', 'Small Molecule', 'JAKi'),
    (12, 'upadacitinib', 'Upadacitinib', 'No', 'JAK inhibitor', 'Small Molecule', 'JAKi'),
    (13, 'filgotinib', 'Filgotinib', 'No', 'JAK inhibitor', 'Small Molecule', 'JAKi'),
    (14, 'ruxolitinib', 'Ruxolitinib', 'No', 'JAK inhibitor', 'Small Molecule', 'JAKi'),
    (15, 'methotrexate', 'Methotrexate', 'No', 'Antimetabolite', 'Small Molecule', 'DHFRi'),
    (16, 'leflunomide', 'Leflunomide', 'No', 'Pyrimidine synthesis inhibitor', 'Small Molecule', 'DHODHi'),
    (17, 'azathioprine', 'Azathioprine', 'No', 'Purine synthesis inhibitor', 'Small Molecule', 'IMPDHi'),
    (18, 'cyclosporine', 'Cyclosporine', 'No', 'Calcineurin inhibitor', 'Small Molecule', 'CNi'),
    (19, 'mycophenolate', 'Mycophenolate', 'No', 'IMPDH inhibitor', 'Small Molecule', 'IMPDHi'),
    (20, 'belimumab', 'Belimumab', 'Yes', 'BLyS inhibitor', 'Biologic', 'BLySi'),
    (21, 'vedolizumab', 'Vedolizumab', 'Yes', 'Integrin inhibitor', 'Biologic', 'Integrini'),
    (22, 'natalizumab', 'Natalizumab', 'Yes', 'Integrin inhibitor', 'Biologic', 'Integrini'),
    (23, 'ustekinumab', 'Ustekinumab', 'Yes', 'IL-12/23 Blocker', 'Biologic', 'IL12/23i'),
    (24, 'canakinumab', 'Canakinumab', 'Yes', 'IL-1 Blocker', 'Biologic', 'IL1i'),
    (25, 'apremilast', 'Apremilast', 'No', 'PDE4 inhibitor', 'Small Molecule', 'PDE4i'),
    (26, 'hydroxychloroquine', 'Hydroxychloroquine', 'No', 'Antimalarial', 'Small Molecule', 'Lysosomotropic'),
    (27, 'sulfasalazine', 'Sulfasalazine', 'No', 'Anti-inflammatory', 'Small Molecule', 'Unknown'),
    (28, 'azithromycin', 'Azithromycin', 'No', 'Macrolide antibiotic', 'Small Molecule', '50S ribosome'),
    (29, 'amoxicillin', 'Amoxicillin', 'No', 'Beta-lactam antibiotic', 'Small Molecule', 'PBPs'),
    (30, 'ciprofloxacin', 'Ciprofloxacin', 'No', 'Fluoroquinolone antibiotic', 'Small Molecule', 'DNA gyrase'),
    (31, 'doxycycline', 'Doxycycline', 'No', 'Tetracycline antibiotic', 'Small Molecule', '30S ribosome'),
    (32, 'clindamycin', 'Clindamycin', 'No', 'Lincosamide antibiotic', 'Small Molecule', '50S ribosome'),
    (33, 'metronidazole', 'Metronidazole', 'No', 'Nitroimidazole antibiotic', 'Small Molecule', 'DNA'),
    (34, 'vancomycin', 'Vancomycin', 'No', 'Glycopeptide antibiotic', 'Small Molecule', 'Cell wall'),
    (35, 'gentamicin', 'Gentamicin', 'No', 'Aminoglycoside antibiotic', 'Small Molecule', '30S ribosome'),
    (36, 'ceftriaxone', 'Ceftriaxone', 'No', 'Cephalosporin antibiotic', 'Small Molecule', 'PBPs'),
    (37, 'piperacillin', 'Piperacillin', 'No', 'Beta-lactam antibiotic', 'Small Molecule', 'PBPs'),
    (38, 'tazobactam', 'Tazobactam', 'No', 'Beta-lactamase inhibitor', 'Small Molecule', 'Beta-lactamase'),
    (39, 'meropenem', 'Meropenem', 'No', 'Carbapenem antibiotic', 'Small Molecule', 'PBPs'),
    (40, 'linezolid', 'Linezolid', 'No', 'Oxazolidinone antibiotic', 'Small Molecule', '50S ribosome'),
    (41, 'oseltamivir', 'Oseltamivir', 'No', 'Neuraminidase inhibitor', 'Small Molecule', 'Neuraminidase'),
    (42, 'sofosbuvir', 'Sofosbuvir', 'No', 'NS5B polymerase inhibitor', 'Small Molecule', 'NS5B'),
    (43, 'ledipasvir', 'Ledipasvir', 'No', 'NS5A inhibitor', 'Small Molecule', 'NS5A'),
    (44, 'efavirenz', 'Efavirenz', 'No', 'NNRTI', 'Small Molecule', 'Reverse transcriptase'),
    (45, 'tenofovir', 'Tenofovir', 'No', 'NRTI', 'Small Molecule', 'Reverse transcriptase'),
    (46, 'emtricitabine', 'Emtricitabine', 'No', 'NRTI', 'Small Molecule', 'Reverse transcriptase'),
    (47, 'abacavir', 'Abacavir', 'No', 'NRTI', 'Small Molecule', 'Reverse transcriptase'),
    (48, 'lamivudine', 'Lamivudine', 'No', 'NRTI', 'Small Molecule', 'Reverse transcriptase'),
    (49, 'zidovudine', 'Zidovudine', 'No', 'NRTI', 'Small Molecule', 'Reverse transcriptase'),
    (50, 'atazanavir', 'Atazanavir', 'No', 'Protease inhibitor', 'Small Molecule', 'HIV protease'),
    (51, 'darunavir', 'Darunavir', 'No', 'Protease inhibitor', 'Small Molecule', 'HIV protease'),
    (52, 'lopinavir', 'Lopinavir', 'No', 'Protease inhibitor', 'Small Molecule', 'HIV protease'),
    (53, 'ritonavir', 'Ritonavir', 'No', 'Protease inhibitor', 'Small Molecule', 'HIV protease'),
    (54, 'raltegravir', 'Raltegravir', 'No', 'Integrase inhibitor', 'Small Molecule', 'HIV integrase'),
    (55, 'dolutegravir', 'Dolutegravir', 'No', 'Integrase inhibitor', 'Small Molecule', 'HIV integrase'),
    (56, 'elvitegravir', 'Elvitegravir', 'No', 'Integrase inhibitor', 'Small Molecule', 'HIV integrase'),
    (57, 'maraviroc', 'Maraviroc', 'No', 'CCR5 antagonist', 'Small Molecule', 'CCR5'),
    (58, 'enfuvirtide', 'Enfuvirtide', 'Yes', 'Fusion inhibitor', 'Peptide', 'gp41'),
    (59, 'ribavirin', 'Ribavirin', 'No', 'Nucleoside analog', 'Small Molecule', 'RNA polymerase'),
    (60, 'remdesivir', 'Remdesivir', 'No', 'RNA polymerase inhibitor', 'Small Molecule', 'RNA polymerase'),
    (61, 'favipiravir', 'Favipiravir', 'No', 'RNA polymerase inhibitor', 'Small Molecule', 'RNA polymerase'),
    (62, 'hydrocortisone', 'Hydrocortisone', 'No', 'Corticosteroid', 'Small Molecule', 'Glucocorticoid receptor'),
    (63, 'prednisone', 'Prednisone', 'No', 'Corticosteroid', 'Small Molecule', 'Glucocorticoid receptor'),
    (64, 'dexamethasone', 'Dexamethasone', 'No', 'Corticosteroid', 'Small Molecule', 'Glucocorticoid receptor'),
    (65, 'fluticasone', 'Fluticasone', 'No', 'Corticosteroid', 'Small Molecule', 'Glucocorticoid receptor'),
    (66, 'budesonide', 'Budesonide', 'No', 'Corticosteroid', 'Small Molecule', 'Glucocorticoid receptor'),
    (67, 'albuterol', 'Albuterol', 'No', 'Beta-2 agonist', 'Small Molecule', 'Beta-2 receptor'),
    (68, 'salmeterol', 'Salmeterol', 'No', 'Beta-2 agonist', 'Small Molecule', 'Beta-2 receptor'),
    (69, 'formoterol', 'Formoterol', 'No', 'Beta-2 agonist', 'Small Molecule', 'Beta-2 receptor'),
    (70, 'ipratropium', 'Ipratropium', 'No', 'Anticholinergic', 'Small Molecule', 'Muscarinic receptor'),
    (71, 'tiotropium', 'Tiotropium', 'No', 'Anticholinergic', 'Small Molecule', 'Muscarinic receptor'),
    (72, 'montelukast', 'Montelukast', 'No', 'Leukotriene receptor antagonist', 'Small Molecule', 'CysLT1 receptor'),
    (73, 'omeprazole', 'Omeprazole', 'No', 'Proton pump inhibitor', 'Small Molecule', 'H+/K+ ATPase'),
    (74, 'pantoprazole', 'Pantoprazole', 'No', 'Proton pump inhibitor', 'Small Molecule', 'H+/K+ ATPase'),
    (75, 'lansoprazole', 'Lansoprazole', 'No', 'Proton pump inhibitor', 'Small Molecule', 'H+/K+ ATPase'),
    (76, 'ranitidine', 'Ranitidine', 'No', 'H2 receptor antagonist', 'Small Molecule', 'H2 receptor'),
    (77, 'famotidine', 'Famotidine', 'No', 'H2 receptor antagonist', 'Small Molecule', 'H2 receptor'),
    (78, 'metformin', 'Metformin', 'No', 'Biguanide', 'Small Molecule', 'AMPK'),
    (79, 'glipizide', 'Glipizide', 'No', 'Sulfonylurea', 'Small Molecule', 'KATP channel'),
    (80, 'glyburide', 'Glyburide', 'No', 'Sulfonylurea', 'Small Molecule', 'KATP channel'),
    (81, 'pioglitazone', 'Pioglitazone', 'No', 'Thiazolidinedione', 'Small Molecule', 'PPAR-gamma'),
    (82, 'rosiglitazone', 'Rosiglitazone', 'No', 'Thiazolidinedione', 'Small Molecule', 'PPAR-gamma'),
    (83, 'sitagliptin', 'Sitagliptin', 'No', 'DPP-4 inhibitor', 'Small Molecule', 'DPP-4'),
    (84, 'linagliptin', 'Linagliptin', 'No', 'DPP-4 inhibitor', 'Small Molecule', 'DPP-4'),
    (85, 'canagliflozin', 'Canagliflozin', 'No', 'SGLT2 inhibitor', 'Small Molecule', 'SGLT2'),
    (86, 'dapagliflozin', 'Dapagliflozin', 'No', 'SGLT2 inhibitor', 'Small Molecule', 'SGLT2'),
    (87, 'empagliflozin', 'Empagliflozin', 'No', 'SGLT2 inhibitor', 'Small Molecule', 'SGLT2'),
    (88, 'liraglutide', 'Liraglutide', 'Yes', 'GLP-1 agonist', 'Peptide', 'GLP-1 receptor'),
    (89, 'exenatide', 'Exenatide', 'Yes', 'GLP-1 agonist', 'Peptide', 'GLP-1 receptor'),
    (90, 'semaglutide', 'Semaglutide', 'Yes', 'GLP-1 agonist', 'Peptide', 'GLP-1 receptor'),
    (91, 'insulin-glargine', 'Insulin Glargine', 'Yes', 'Long-acting insulin', 'Protein', 'Insulin receptor'),
    (92, 'insulin-aspart', 'Insulin Aspart', 'Yes', 'Rapid-acting insulin', 'Protein', 'Insulin receptor'),
    (93, 'insulin-lispro', 'Insulin Lispro', 'Yes', 'Rapid-acting insulin', 'Protein', 'Insulin receptor'),
    (94, 'insulin-detemir', 'Insulin Detemir', 'Yes', 'Long-acting insulin', 'Protein', 'Insulin receptor'),
    (95, 'warfarin', 'Warfarin', 'No', 'Vitamin K antagonist', 'Small Molecule', 'VKOR'),
    (96, 'apixaban', 'Apixaban', 'No', 'Factor Xa inhibitor', 'Small Molecule', 'Factor Xa'),
    (97, 'rivaroxaban', 'Rivaroxaban', 'No', 'Factor Xa inhibitor', 'Small Molecule', 'Factor Xa'),
    (98, 'dabigatran', 'Dabigatran', 'No', 'Direct thrombin inhibitor', 'Small Molecule', 'Thrombin'),
    (99, 'clopidogrel', 'Clopidogrel', 'No', 'P2Y12 inhibitor', 'Small Molecule', 'P2Y12 receptor'),
    (100, 'sarilumab', 'Sarilumab', 'Yes', 'IL-6 Blocker', 'Biologic', 'IL6i');

COMMIT; 