-- Demo Data: Generic Aliases (3-30 per generic drug)
-- Run after generic_drugs insert

BEGIN;

-- Adalimumab aliases
INSERT INTO generic_aliases (row, generic_key, generic_uid, alias) VALUES
    (1, 'adalimumab', NULL, 'adalimumab'),
    (2, 'adalimumab', NULL, 'humira'),
    (3, 'adalimumab', NULL, 'd2e7'),
    (4, 'adalimumab', NULL, 'anti-tnf'),
    (5, 'adalimumab', NULL, 'tnf blocker'),
    (6, 'adalimumab', NULL, 'tnf inhibitor'),
    (7, 'adalimumab', NULL, 'tnf-alpha blocker'),
    (8, 'adalimumab', NULL, 'tnf-alpha inhibitor'),
    (9, 'adalimumab', NULL, 'anti-tnf-alpha'),
    (10, 'adalimumab', NULL, 'tnf antibody'),
    (11, 'adalimumab', NULL, 'tnf monoclonal antibody'),
    (12, 'adalimumab', NULL, 'tnf mab'),
    (13, 'adalimumab', NULL, 'tnf-alpha antibody'),
    (14, 'adalimumab', NULL, 'tnf-alpha monoclonal antibody'),
    (15, 'adalimumab', NULL, 'tnf-alpha mab'),
    (16, 'adalimumab', NULL, 'anti-tnf monoclonal antibody'),
    (17, 'adalimumab', NULL, 'anti-tnf-alpha monoclonal antibody'),
    (18, 'adalimumab', NULL, 'tnf-alpha blocker antibody'),
    (19, 'adalimumab', NULL, 'tnf-alpha inhibitor antibody'),
    (20, 'adalimumab', NULL, 'tnf-alpha neutralizing antibody'),
    (21, 'adalimumab', NULL, 'tnf-alpha binding antibody'),
    (22, 'adalimumab', NULL, 'tnf-alpha specific antibody'),
    (23, 'adalimumab', NULL, 'tnf-alpha targeted antibody'),
    (24, 'adalimumab', NULL, 'tnf-alpha directed antibody'),
    (25, 'adalimumab', NULL, 'tnf-alpha selective antibody'),
    (26, 'adalimumab', NULL, 'tnf-alpha blocking antibody'),
    (27, 'adalimumab', NULL, 'tnf-alpha inhibitory antibody'),
    (28, 'adalimumab', NULL, 'tnf-alpha antagonist antibody'),
    (29, 'adalimumab', NULL, 'tnf-alpha neutralizing monoclonal antibody'),
    (30, 'adalimumab', NULL, 'tnf-alpha binding monoclonal antibody');

-- Infliximab aliases
INSERT INTO generic_aliases (row, generic_key, generic_uid, alias) VALUES
    (31, 'infliximab', NULL, 'infliximab'),
    (32, 'infliximab', NULL, 'remicade'),
    (33, 'infliximab', NULL, 'c5b'),
    (34, 'infliximab', NULL, 'anti-tnf'),
    (35, 'infliximab', NULL, 'tnf blocker'),
    (36, 'infliximab', NULL, 'tnf inhibitor'),
    (37, 'infliximab', NULL, 'tnf-alpha blocker'),
    (38, 'infliximab', NULL, 'tnf-alpha inhibitor'),
    (39, 'infliximab', NULL, 'anti-tnf-alpha'),
    (40, 'infliximab', NULL, 'tnf antibody'),
    (41, 'infliximab', NULL, 'tnf monoclonal antibody'),
    (42, 'infliximab', NULL, 'tnf mab'),
    (43, 'infliximab', NULL, 'tnf-alpha antibody'),
    (44, 'infliximab', NULL, 'tnf-alpha monoclonal antibody'),
    (45, 'infliximab', NULL, 'tnf-alpha mab'),
    (46, 'infliximab', NULL, 'anti-tnf monoclonal antibody'),
    (47, 'infliximab', NULL, 'anti-tnf-alpha monoclonal antibody'),
    (48, 'infliximab', NULL, 'tnf-alpha blocker antibody'),
    (49, 'infliximab', NULL, 'tnf-alpha inhibitor antibody'),
    (50, 'infliximab', NULL, 'tnf-alpha neutralizing antibody'),
    (51, 'infliximab', NULL, 'tnf-alpha binding antibody'),
    (52, 'infliximab', NULL, 'tnf-alpha specific antibody'),
    (53, 'infliximab', NULL, 'tnf-alpha targeted antibody'),
    (54, 'infliximab', NULL, 'tnf-alpha directed antibody'),
    (55, 'infliximab', NULL, 'tnf-alpha selective antibody'),
    (56, 'infliximab', NULL, 'tnf-alpha blocking antibody'),
    (57, 'infliximab', NULL, 'tnf-alpha inhibitory antibody'),
    (58, 'infliximab', NULL, 'tnf-alpha antagonist antibody'),
    (59, 'infliximab', NULL, 'tnf-alpha neutralizing monoclonal antibody'),
    (60, 'infliximab', NULL, 'tnf-alpha binding monoclonal antibody');

-- Etanercept aliases
INSERT INTO generic_aliases (row, generic_key, generic_uid, alias) VALUES
    (61, 'etanercept', NULL, 'etanercept'),
    (62, 'etanercept', NULL, 'enbrel'),
    (63, 'etanercept', NULL, 'tnf receptor fusion protein'),
    (64, 'etanercept', NULL, 'tnf-r-fc'),
    (65, 'etanercept', NULL, 'tnf receptor fc fusion protein'),
    (66, 'etanercept', NULL, 'tnf-alpha receptor fusion protein'),
    (67, 'etanercept', NULL, 'tnf-alpha-r-fc'),
    (68, 'etanercept', NULL, 'tnf-alpha receptor fc fusion protein'),
    (69, 'etanercept', NULL, 'anti-tnf'),
    (70, 'etanercept', NULL, 'tnf blocker'),
    (71, 'etanercept', NULL, 'tnf inhibitor'),
    (72, 'etanercept', NULL, 'tnf-alpha blocker'),
    (73, 'etanercept', NULL, 'tnf-alpha inhibitor'),
    (74, 'etanercept', NULL, 'anti-tnf-alpha'),
    (75, 'etanercept', NULL, 'tnf receptor blocker'),
    (76, 'etanercept', NULL, 'tnf receptor inhibitor'),
    (77, 'etanercept', NULL, 'tnf-alpha receptor blocker'),
    (78, 'etanercept', NULL, 'tnf-alpha receptor inhibitor'),
    (79, 'etanercept', NULL, 'anti-tnf receptor'),
    (80, 'etanercept', NULL, 'anti-tnf-alpha receptor'),
    (81, 'etanercept', NULL, 'tnf receptor fusion'),
    (82, 'etanercept', NULL, 'tnf-alpha receptor fusion'),
    (83, 'etanercept', NULL, 'tnf-r fusion protein'),
    (84, 'etanercept', NULL, 'tnf-alpha-r fusion protein'),
    (85, 'etanercept', NULL, 'tnf receptor fc'),
    (86, 'etanercept', NULL, 'tnf-alpha receptor fc'),
    (87, 'etanercept', NULL, 'tnf-r-fc fusion'),
    (88, 'etanercept', NULL, 'tnf-alpha-r-fc fusion'),
    (89, 'etanercept', NULL, 'tnf receptor immunoglobulin fusion'),
    (90, 'etanercept', NULL, 'tnf-alpha receptor immunoglobulin fusion');

-- Rituximab aliases
INSERT INTO generic_aliases (row, generic_key, generic_uid, alias) VALUES
    (91, 'rituximab', NULL, 'rituximab'),
    (92, 'rituximab', NULL, 'rituxan'),
    (93, 'rituximab', NULL, 'anti-cd20'),
    (94, 'rituximab', NULL, 'cd20 antibody'),
    (95, 'rituximab', NULL, 'cd20 monoclonal antibody'),
    (96, 'rituximab', NULL, 'cd20 mab'),
    (97, 'rituximab', NULL, 'anti-cd20 antibody'),
    (98, 'rituximab', NULL, 'anti-cd20 monoclonal antibody'),
    (99, 'rituximab', NULL, 'anti-cd20 mab'),
    (100, 'rituximab', NULL, 'cd20 blocker'),
    (101, 'rituximab', NULL, 'cd20 inhibitor'),
    (102, 'rituximab', NULL, 'cd20 targeted antibody'),
    (103, 'rituximab', NULL, 'cd20 directed antibody'),
    (104, 'rituximab', NULL, 'cd20 specific antibody'),
    (105, 'rituximab', NULL, 'cd20 selective antibody'),
    (106, 'rituximab', NULL, 'cd20 binding antibody'),
    (107, 'rituximab', NULL, 'cd20 neutralizing antibody'),
    (108, 'rituximab', NULL, 'cd20 blocking antibody'),
    (109, 'rituximab', NULL, 'cd20 inhibitory antibody'),
    (110, 'rituximab', NULL, 'cd20 antagonist antibody'),
    (111, 'rituximab', NULL, 'cd20 neutralizing monoclonal antibody'),
    (112, 'rituximab', NULL, 'cd20 binding monoclonal antibody'),
    (113, 'rituximab', NULL, 'cd20 targeted monoclonal antibody'),
    (114, 'rituximab', NULL, 'cd20 directed monoclonal antibody'),
    (115, 'rituximab', NULL, 'cd20 specific monoclonal antibody'),
    (116, 'rituximab', NULL, 'cd20 selective monoclonal antibody'),
    (117, 'rituximab', NULL, 'cd20 blocking monoclonal antibody'),
    (118, 'rituximab', NULL, 'cd20 inhibitory monoclonal antibody'),
    (119, 'rituximab', NULL, 'cd20 antagonist monoclonal antibody'),
    (120, 'rituximab', NULL, 'cd20 neutralizing mab'),
    (121, 'rituximab', NULL, 'cd20 binding mab'),
    (122, 'rituximab', NULL, 'cd20 targeted mab'),
    (123, 'rituximab', NULL, 'cd20 directed mab'),
    (124, 'rituximab', NULL, 'cd20 specific mab'),
    (125, 'rituximab', NULL, 'cd20 selective mab'),
    (126, 'rituximab', NULL, 'cd20 blocking mab'),
    (127, 'rituximab', NULL, 'cd20 inhibitory mab'),
    (128, 'rituximab', NULL, 'cd20 antagonist mab'),
    (129, 'rituximab', NULL, 'cd20 neutralizing monoclonal'),
    (130, 'rituximab', NULL, 'cd20 binding monoclonal');

-- Continue with more aliases for remaining generics...
-- This sample shows the pattern. The full file will contain thousands of entries.

COMMIT; 